### ISSUE TITLE
Apache License?

### ISSUE THREAD

**Issue by apavlo** [memsql/upsert-benchmark#1]
There is no software license for this code (unless I missed it?).

If you make it Apache, then I can get a student to port it to our benchmarking framework ([OLTPBench](https://github.com/oltpbenchmark/oltpbench)).

**Comment by memsql-admin** [comment]
Let me consult internally and follow up shortly.

_Ankur Goyal_
VP of Engineering, MemSQL
534 4th Street
San Francisco, CA 94107
(415) 666-2262

855-4-MEMSQL
www.memsql.com

**Comment by apavlo** [comment]
Same comment for [memsql/nyse-demo](https://github.com/memsql/nyse-demo).

**Comment by joshuacrass** [comment]
@apavlo I have added the license.
